name: Deno Formatting

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run deno fmt
        run: |
          deno fmt
      - name: Run deno lint
        run: |
          deno lint
